### ISSUE TITLE
XCode Target + Config(deug/release/...)

### ISSUE THREAD

**Issue by yume190** [XCodeBazelize/Bazelize#3]
```yaml
# XCode Setting
debug:
  SDKROOT: iphoneos
  SDKROOT[arch=x86_64]: iphoneos
release:
  SDKROOT: iphoneos
  SDKROOT[arch=x86_64]: iphoneos
```
